- name: Install Google APT Key
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
# - name: Install Google APT Key
#   ansible.builtin.command:
#     cmd: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- name: Add Google Chrome Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: chrome.list
    state: present
    update_cache: true
- name: Install Microsoft APT Key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: Add VSCode repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    filename: vscode.list
    state: present
    update_cache: true
# - name: Download Microsoft APT Key
#   ansible.builtin.command:
#     cmd: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/packages.microsoft.gpg
# - name: Install Microsoft APT Key
#   ansible.builtin.command:
#     command: install -D -o root -g root -m 644 /tmp/packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
- name: Install Github CLI
  block:
    - name: Get Github CLI Repository Key
      ansible.builtin.get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    - name: Create Github CLI Repository
      ansible.builtin.apt_respository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
        filename: github-cli.list
        state: present
        update_cache: true
- name: Get Discord Debian Installer
  ansible.builtin.get_url:
    url: https://discord.com/api/download?platform=linux&format=deb
    dest: /tmp/discord.deb
- name: Install Packages
  ansible.builtin.apt:
    name:
      - code
      - google-chrome-stable
      - nala
      - gh
    state: present
- name: Install Discord
  ansible.builtin.apt:
    deb: /tmp/discord.deb
    state: present