- name: Install Google APT Key
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
- name: Add Google Chrome Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: chrome.list
    state: present
    update_cache: true
- name: Install Microsoft APT Key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: Add VSCode repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
    filename: vscode.list
    state: present
    update_cache: true
- name: Install Github CLI
  block:
    - name: Get Github CLI Repository Key
      ansible.builtin.get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    - name: Create Github CLI Repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
        filename: github-cli.list
        state: present
        update_cache: true
- name: Get Discord Debian Installer
  ansible.builtin.get_url:
    url: https://discord.com/api/download?platform=linux&format=deb
    dest: /tmp/discord.deb
- name: Install Packages
  ansible.builtin.apt:
    name:
      - vim
      - code
      - google-chrome-stable
      - nala
      - gh
    state: present
- name: Install Discord
  ansible.builtin.apt:
    deb: /tmp/discord.deb
    state: present
- name: Copy wallpaper
  ansible.builtin.copy:
    src: samurai-wallpaper1080p.jpg
    dest: /home/grimdark/Pictures/samurai-wallpaper1080p.jpg 
- name: Set wallpaper
  command:
    cmd: gsettings set org.cinnamon.desktop.background picture-uri "file:///home/grimdark/Pictures/samurai-wallpaper1080p.jpg"
